name: 'Linear update action'
description: 'Update linear issue state from github'
inputs:
  linear-api-key:
    description: 'Linear api key'
    required: true
  linear-team-key:
    description: 'Linear team key - Eg - PRO, MVP, etc'
    required: true
  state-from:
    description: 'The name of the state of issues to search for'
    required: true
  state-to:
    description: 'The name of the state to set the issues to'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
