on:
  release:
    types: [published]
  workflow_dispatch:

name: Linear status update test

jobs:
  linear_update:
    name: Update linear status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linear update
        uses: phenax/linear-state-update-action@latest
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}
          linear-team-key: AKS
          state-from: 'Approved'
          state-to: 'Done'
